### ISSUE TITLE
Segmentation Fault when loading ROM - No sound driver preselected

### ISSUE THREAD

**Issue by Ferlonas** [visualboyadvance-m/visualboyadvance-m#312]
### Expected behavior
Rom loads and starts up

### Actual behavior
vbam crashes with segfault

### Steps to reproduce the behavior
Compiled latest version (2.1.0 - commit 58083d9d4aa5f9636fcd4971164d877a92278d94)
Tried to load ROM (doesn't matter if .gba or .gb)
segfault

### Crash bugs
If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.
Core was generated by `./visualboyadvance-m'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000005f2f86 in soundReset () at /home/fschaefer/Downloads/sources/visualboyadvance-m/src/gba/Sound.cpp:521
521	    soundDriver->reset();
(gdb) bt
#0  0x00000000005f2f86 in soundReset () at /home/fschaefer/Downloads/sources/visualboyadvance-m/src/gba/Sound.cpp:521
#1  0x0000000000573f3a in CPUReset () at /home/fschaefer/Downloads/sources/visualboyadvance-m/src/gba/GBA.cpp:3620
#2  0x0000000000525a7b in GameArea::LoadGame (this=0x24f9460, name=...) at /home/fschaefer/Downloads/sources/visualboyadvance-m/src/wx/panel.cpp:292
#3  0x00000000004f39db in MainFrame::OnwxID_FILE1 (this=0x23312f0) at /home/fschaefer/Downloads/sources/visualboyadvance-m/src/wx/cmdevents.cpp:198
#4  0x00007f8aba99811e in wxAppConsoleBase::CallEventHandler (this=0x2014910, handler=0x23312f0, functor=..., event=...) at ../src/common/appbase.cpp:623
#5  0x00007f8abab0b282 in wxEvtHandler::ProcessEventIfMatchesId (entry=..., handler=<optimized out>, event=...) at ../src/common/event.cpp:1384
#6  0x00007f8abab0b333 in wxEventHashTable::HandleEvent (this=<optimized out>, event=..., self=self@entry=0x23312f0) at ../src/common/event.cpp:990
#7  0x00007f8abab0b68d in wxEvtHandler::TryHereOnly (this=this@entry=0x23312f0, event=...) at ../src/common/event.cpp:1581
#8  0x00007f8abab0b703 in TryBeforeAndHere (event=..., this=this@entry=0x23312f0) at ../include/wx/event.h:3671
#9  wxEvtHandler::ProcessEventLocally (this=this@entry=0x23312f0, event=...) at ../src/common/event.cpp:1514
#10 0x00007f8abab0b765 in wxEvtHandler::ProcessEvent (this=0x23312f0, event=...) at ../src/common/event.cpp:1487
#11 0x00007f8abb199a48 in wxWindowBase::TryAfter (this=0x2384390, event=...) at ../src/common/wincmn.cpp:3427
#12 0x00007f8abab0b4f7 in wxEvtHandler::SafelyProcessEvent (this=<optimized out>, event=...) at ../src/common/event.cpp:1605
#13 0x00007f8abb19ae9c in wxWindowBase::HandleWindowEvent (this=this@entry=0x2384390, event=...) at ../src/common/wincmn.cpp:1525
#14 0x00007f8abb15e327 in wxMenuBase::SendEvent (this=this@entry=0x2395f70, itemid=<optimized out>, checked=<optimized out>) at ../src/common/menucmn.cpp:666
#15 0x00007f8abb08ef5b in menuitem_activate (item=0x23b92a0) at ../src/gtk/menu.cpp:552
#16 0x00007f8ab4b293b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f8ab4b3ad3d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f8ab4b42a29 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f8ab4b42ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f8ab56c74fc in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#21 0x00007f8ab55c9fdd in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#22 0x00007f8ab55ca32c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#23 0x00007f8ab55b8815 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00007f8ab4b293b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007f8ab4b3aafb in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007f8ab4b426f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007f8ab4b42ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007f8ab56c8684 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#29 0x00007f8ab55b6fc4 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#30 0x00007f8ab55b737b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#31 0x00007f8ab52313ec in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#32 0x00007f8ab4859e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007f8ab485a048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007f8ab485a30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007f8ab55b6447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#36 0x00007f8abb024145 in wxGUIEventLoop::DoRun (this=0x20c4910) at ../src/gtk/evtloop.cpp:65
#37 0x00007f8aba9da440 in wxEventLoopBase::Run (this=0x20c4910) at ../src/common/evtloopcmn.cpp:78
#38 0x00007f8aba99a1fd in wxAppConsoleBase::MainLoop (this=0x2014910) at ../src/common/appbase.cpp:334
#39 0x00007f8abaa2604d in wxEntry (argc=@0x7f8abadb3190: 1, argv=<optimized out>) at ../src/common/init.cpp:495
Segmentation fault (core dumped)

### ROM details

No games found that are not affected. Error first occured with Megaman Battle Network

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):
none selected. selecting SDL fixed the issue. I decided to open this ticket anyway so that you could decide whether to harden the code here or discard it.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Linux 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 17.2 Rafaela

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"):
58083d9d4aa5f9636fcd4971164d877a92278d94

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:
Attached output of make (including warnings)
[segfault.tar.gz](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2396988/segfault.tar.gz)

**Comment by rkitover** [comment]
Currently we rely on the sound driver to control the game speed, not having one will not work.

We need to make some sort of "null" sound driver, for people without sound hardware or people who don't want sound.
