### ISSUE TITLE
Crash on Hamtaro - Ham-Ham Heartbreak

### ISSUE THREAD

**Issue by phoe** [visualboyadvance-m/visualboyadvance-m#707]
### Expected behavior

No crash.

### Actual behavior

```
/usr/include/wx-3.0/wx/longlong.h:118:36: runtime error: left shift of negative value -2147483648
Loaded battery /home/phoe/Downloads/Hamtaro - Ham-Ham Heartbreak (USA).sav
=================================================================
==96742==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55fc9cdfbf3c at pc 0x55fc9a74fa42 bp 0x7fff4251fd40 sp 0x7fff4251fd38
READ of size 4 at 0x55fc9cdfbf3c thread T0
    #0 0x55fc9a74fa41 in gfxDrawSprites(unsigned int*) [clone .constprop.5] ../src/gba/GBAGfx.h:1108
    #1 0x55fc9a084c6b in mode0RenderLineNoWindow() ../src/gba/Mode0.cpp:144
    #2 0x55fc99cad469 in CPULoop(int) ../src/gba/GBA.cpp:3900
    #3 0x55fc99cb5a76 in gbaEmulate(int) ../src/gba/GBA.cpp:4253
    #4 0x55fc9998a0e7 in GameArea::OnIdle(wxIdleEvent&) ../src/wx/panel.cpp:1129
    #5 0x7fac1c02f240 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a240)
    #6 0x7fac1c02f332 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a332)
    #7 0x7fac1c02f67b in wxEvtHandler::TryHereOnly(wxEvent&) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a67b)
    #8 0x7fac1c02f702 in wxEvtHandler::ProcessEventLocally(wxEvent&) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a702)
    #9 0x7fac1c02f7a0 in wxEvtHandler::ProcessEvent(wxEvent&) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a7a0)
    #10 0x7fac1c02f536 in wxEvtHandler::SafelyProcessEvent(wxEvent&) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x20a536)
    #11 0x7fac1c567bae in wxWindowBase::SendIdleEvents(wxIdleEvent&) (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x47ebae)
    #12 0x7fac1c567b87 in wxWindowBase::SendIdleEvents(wxIdleEvent&) (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x47eb87)
    #13 0x7fac1c3fe3fe in wxFrame::SendIdleEvents(wxIdleEvent&) (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x3153fe)
    #14 0x7fac1c43e0dc in wxAppBase::ProcessIdle() (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x3550dc)
    #15 0x7fac1c36ea74 in wxApp::DoIdle() (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x285a74)
    #16 0x7fac1c36eb62  (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x285b62)
    #17 0x7fac183334dd in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x504dd)
    #18 0x7fac1833388f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5088f)
    #19 0x7fac18333b62 in g_main_loop_run (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x50b62)
    #20 0x7fac1b44ae84 in gtk_main (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0+0x23de84)
    #21 0x7fac1c38b954 in wxGUIEventLoop::DoRun() (/usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0+0x2a2954)
    #22 0x7fac1beee97c in wxEventLoopBase::Run() (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0xc997c)
    #23 0x7fac1beb79a5 in wxAppConsoleBase::MainLoop() (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x929a5)
    #24 0x7fac1bf3fa18 in wxEntry(int&, wchar_t**) (/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0+0x11aa18)
    #25 0x55fc9930dcca in main ../src/wx/wxvbam.cpp:32
    #26 0x7fac186c1e0a in __libc_start_main ../csu/libc-start.c:308
    #27 0x55fc993e1b79 in _start (/tmp/visualboyadvance-m/build/visualboyadvance-m+0x1e3cb79)

0x55fc9cdfbf3c is located 4 bytes to the left of global variable 'lineOBJ' defined in '../src/gba/GBAGfx.cpp:14:10' (0x55fc9cdfbf40) of size 960
0x55fc9cdfbf3c is located 28 bytes to the right of global variable 'lineOBJWin' defined in '../src/gba/GBAGfx.cpp:15:10' (0x55fc9cdfbb60) of size 960
SUMMARY: AddressSanitizer: global-buffer-overflow ../src/gba/GBAGfx.h:1108 in gfxDrawSprites(unsigned int*) [clone .constprop.5]
Shadow bytes around the buggy address:
  0x0ac0139b7790: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b77a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b77b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b77c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b77d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ac0139b77e0: 00 00 00 00 f9 f9 f9[f9]00 00 00 00 00 00 00 00
  0x0ac0139b77f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b7800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b7810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b7820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac0139b7830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==96742==ABORTING
```

### Steps to reproduce the behavior

Launch the game, go past the naming screen. Finish the dream sequence, talk to Boss, try going down the stairs.

### ROM details

`Hamtaro - Ham-Ham Heartbreak (USA).gba` - md5 `42cca53c94c0bb8e5146631945bf0cd9`

### Option details

opengl hq2x / sdl

### Build details

debian sid x86_64 xorg, VBA-M built from current master.

**Comment by denisfa** [comment]
@phoe Thank you for the report. I am going to guess that you are using a GBA BIOS file, right? Also, just for confirmation, what compiler did you use?

**Comment by phoe** [comment]
I do not think that I am using any GBA BIOS file. Where do I check?

It seems that GCC10 was used to compile vba-m.

**Comment by negativeExponent** [comment]
vbam has a lot of these errors caused by offscreen drawing especially when using asan. this one is pixel offset during mosaic effects.
