### ISSUE TITLE
Cannot set gdb breakpoint when attached to GBA ROM.

### ISSUE THREAD

**Issue by GimmeAUnicorn** [visualboyadvance-m/visualboyadvance-m#760]
### Expected behavior
When running the emulator through gdb having the first break in rom.
### Actual behavior
Breaks at 0x00
### Steps to reproduce the behavior
gdb
target remote | VisualBoyAdvance -Gpipe game.gba

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA custom CTF rom
GBA Pokemon Emerald Version

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/62118469/95000833-8d764780-05c4-11eb-9a06-582f25218c02.png)

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Ubuntu 20.04.1 LTS
If using Linux, specify if using xorg or Wayland:
xorg
Version of code (pre-built binary version, or commit ref, or just "master"):
master

**Comment by rkitover** [comment]
If you are trying to attach gdb to a GBA ROM, you need an ARMv7 version of gdb.

Then attach the gdb to the port you configure in the UI.

I don't know much more about this process, I have never tried it myself. A few years ago someone sent a patch to get it to work again, I have no idea if it still works now.

I'd appreciate some help looking into this.

**Comment by GimmeAUnicorn** [comment]
Hey, thanks for your hint ! 

Indeed I needed ARMv7 version of gdb .
Realized today I was in i386....

For the other people that will maybe read this you need to install gdb-multiarch and set architecture ARMv7.

**Comment by GimmeAUnicorn** [comment]
Back for some news !
Attaching gdb works kinda fine.

I open gdb-multiarch, sets arch to armv7, open up visualboyadvance-m, enables break on load, load the rom, target remote localhost:55555, it breaks at 0x08000000 so that's okay. But i'm not able to set a breakpoint.
![image](https://user-images.githubusercontent.com/62118469/95015098-69aa1480-064b-11eb-8afe-f289b9a88d40.png)

If i do it via pipe (target remote | VisualBoyAdvance -Gpipe firmware.gba) He just don't stops at the breakpoints. 

Any idea ?

**Comment by rkitover** [comment]
It looks like we'll need to update the gdb protocol support.

**Comment by GimmeAUnicorn** [comment]
Any ETA?

**Comment by rkitover** [comment]
I'll try to look at this over the next few days.

**Comment by rkitover** [comment]
Hey @GimmeAUnicorn just looking at this now, I tried this with my +multitarget gdb on gentoo, and I get somewhat different results, though it still does not seem to work correctly:

```
✔  ~ 
rkitover@epyc  ➤  gdb
GNU gdb (Gentoo 9.2 vanilla) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target remote localhost:55555localhost:55555: Время ожидания соединения истекло.
(gdb) set architecture armv7
The target architecture is assumed to be armv7
(gdb) target remote localhost:55555
Remote debugging using localhost:55555
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x080383cc in ?? ()
(gdb) where
#0  0x080383cc in ?? ()
#1  0x080387e8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) dis
(gdb) where
#0  0x080383cc in ?? ()
#1  0x080387e8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) disassemble
No function contains program counter for selected frame.
(gdb) break *0x030001fc
Breakpoint 1 at 0x30001fc
(gdb) continue
Continuing.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x080387e2 in ?? ()
(gdb) break *0x080383cc
Breakpoint 2 at 0x80383cc
(gdb) delete 2
(gdb) delete 1
(gdb) delete 1
No breakpoint number 1.
(gdb) break *0x080383cc
Breakpoint 3 at 0x80383cc
(gdb) continue
Continuing.
Remote connection closed
(gdb) target remote localhost:55555
Remote debugging using localhost:55555
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00000018 in ?? ()
(gdb) where
#0  0x00000018 in ?? ()
(gdb) continue
Continuing.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x08038810 in ?? ()
(gdb) break *0x08038810
Breakpoint 4 at 0x8038810
(gdb) continue
Continuing.
Breakpoint (on Thumb) address 08038812

where
continue
<-- frozen here
```

I did not get a protocol error, and it stopped at the breakpoint, but did not return control to gdb.

What version of gdb are you using?

**Comment by GimmeAUnicorn** [comment]
I'm using GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2 mainly but I tried it with gdb-multiarch too

**Comment by rkitover** [comment]
Can you point me to a ROM name (but not the link) and give me some addresses I can use to test breakpoints?

**Comment by GimmeAUnicorn** [comment]
I'm using a custom rom made for a CTF. Unless sending you the ROM I can't do something else :/

**Comment by rkitover** [comment]
If the ROM is legally distributable, then yeah give me a link and some breakpoints to test. We just don't want people posting game ROMs here, for legal reasons.
